### ISSUE TITLE
possível bug - ao incluir disciplina INF019 em Meu Calendário

### ISSUE THREAD

**Issue by leotavo** [LuizHenriqueLobo1/find-your-class-front#2]
Ao incluir a disciplina INF019 a grade horária é preenchida também com a disciplina INF405 - T01. Também não dá opção de escolher a turma 2 de INF019.

![image](https://github.com/user-attachments/assets/a2b61e8e-6e1f-47f4-9563-b57c23fbf9f7)

**Comment by leotavo** [comment]
complementando. aparentemente INF405 - T01 (Sistemas de Informação II) e INF019 - T02 (Gerência de Projetos) são na prática a mesma turma mas com nomes de disciplinas diferentes pra cada curso (Administração; Análise e Desenvolvimento de Sistemas). Mesmos dias, horários, locais e professor (https://portal.ifba.edu.br/salvador/documentos/comunicados/horarios-2024-2-ensino-superior-gra3.pdf).   Mas ao mostrar INF405 em vez de INF019 isso pode causar uma certa confusão ao estudante que não tem conhecimento dessa informação.

**Comment by LuizHenriqueLobo1** [comment]
Então, hoje a identificação da disciplina é realizada através dos códigos extraídos diretamente da planilha, como você relatou acima, já que as disciplinas compartilham sala, dia, horário e professor acaba acontecendo isso.
![image](https://github.com/user-attachments/assets/2a2310b3-19cb-4677-9bb2-9c0510d13742)

**Comment by LuizHenriqueLobo1** [comment]
Vou adicionar um tooltip que ao passar o mouse/clicar mostre o código completo da disciplina que está ocupando aquele dia/sala/horário.

**Comment by LuizHenriqueLobo1** [comment]
Adicionei um wrap no texto da tag da disciplina, isso resolveu o problema de visualização do(s) código(s) da(s) disciplina(s).
